<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - HotelMerlin.com</title>
        <meta name="robots" content="noindex,follow"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css">
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; font-size: 14px; color: #333; margin: 0; padding: 0; background: #f7f7f7; }
          #content { max-width: 1100px; margin: 0 auto; padding: 30px; }
          h1 { font-size: 24px; margin: 0 0 10px; color: #111; font-weight: 600; }
          .description { font-size: 13px; color: #555; margin-bottom: 20px; line-height: 1.6; }
          .description a { color: #0073aa; text-decoration: none; }
          .description a:hover { text-decoration: underline; }
          #sitemap { background: #fff; border: 1px solid #e5e5e5; border-radius: 4px; overflow: hidden; box-shadow: 0 1px 2px rgba(0,0,0,0.04); }
          table { width: 100%; border-collapse: collapse; }
          th { background: #f1f1f1; text-align: left; padding: 12px 18px; font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: #555; border-bottom: 1px solid #e5e5e5; }
          td { padding: 12px 18px; border-bottom: 1px solid #f0f0f0; vertical-align: middle; }
          tr:last-child td { border-bottom: none; }
          tr:hover td { background: #fafafa; }
          a { color: #0073aa; text-decoration: none; }
          a:hover { text-decoration: underline; }
          .small { font-size: 12px; color: #999; }
          #footer { text-align: center; padding: 20px; font-size: 12px; color: #888; }
          #footer a { color: #0073aa; }
        </style>
      </head>
      <body>
        <div id="content">
          <h1>XML Sitemap</h1>
          <p class="description">
            Generated by <a href="https://hotelmerlin.com" target="_blank">HotelMerlin.com SEO</a>, this is an XML Sitemap, meant for consumption by search engines.<br/>
            You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.
          </p>
          <xsl:choose>
            <xsl:when test="sitemap:sitemapindex">
              <p class="description">
                This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
              </p>
              <div id="sitemap">
                <table>
                  <thead>
                    <tr>
                      <th width="75%">Sitemap</th>
                      <th width="25%">Last Modified</th>
                    </tr>
                  </thead>
                  <tbody>
                    <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                      <tr>
                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                        <td><xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/></td>
                      </tr>
                    </xsl:for-each>
                  </tbody>
                </table>
              </div>
            </xsl:when>
            <xsl:otherwise>
              <p class="description">
                This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
              </p>
              <div id="sitemap">
                <table>
                  <thead>
                    <tr>
                      <th width="55%">URL</th>
                      <th width="10%">Images</th>
                      <th width="10%">Priority</th>
                      <th width="10%">Change Freq.</th>
                      <th width="15%">Last Modified</th>
                    </tr>
                  </thead>
                  <tbody>
                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                      <tr>
                        <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                        <td><xsl:value-of select="count(*[local-name()='image'])"/></td>
                        <td><xsl:value-of select="sitemap:priority"/></td>
                        <td><xsl:value-of select="sitemap:changefreq"/></td>
                        <td><xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/></td>
                      </tr>
                    </xsl:for-each>
                  </tbody>
                </table>
              </div>
            </xsl:otherwise>
          </xsl:choose>
          <div id="footer">
            Generated with ❤ by HotelMerlin.com — <a href="https://hotelmerlin.com">hotelmerlin.com</a>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
